name: Calculator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - name: Compile tests
      run: |
        gcc -o calculator_test \
        tests/test_calculator.c \
        src/calculator.c \
        tests/unity.c \
        -I include \
        -I tests \
        -lm

    - name: Run tests
      run: ./calculator_test

  test-windows:
    runs-on: windows-latest
    needs: test-ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MinGW
      run: |
        choco install mingw
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

    - name: Compile tests
      run: |
        gcc -o calculator_test.exe \
        tests/test_calculator.c \
        src/calculator.c \
        tests/unity.c \
        -I include \
        -I tests \
        -lm

    - name: Run tests
      run: .\calculator_test.exe
